apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: acdc-static-image

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: nginx-html
    files:
    - html/